# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20160715_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
