# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_posts_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='Category',
            new_name='category',
        ),
    ]
